### ISSUE TITLE
Possible bug when {frontmatter} is not included

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#37]
New issue: if the \maketitle \begin{abstract}...\end{abstract} is not stated between \begin{frontmatter} and \end{frontmatter}, the entire document is rendered single column.

It's easy to spot and fix; question is whether there should be a warning or compilation error.

**Comment by davidlmobley** [comment]
In general I'm all for having things tell people what the problem is, but I have no idea how easy this is to achieve with LaTeX...

**Comment by davidlmobley** [comment]
Do you know whether this is easily achievable?

**Comment by dwsideriusNIST** [comment]
Nope, this is far deeper into LaTeX than I usually dig.

**Comment by davidlmobley** [comment]
@liantze any insights?

**Comment by liantze** [comment]
That's right, and this is by design, not a bug—the `abstract` must be within `frontmatter` for the title/author/blurb/abstract to be rendered in the current layout. 

And yes, I can make it throw an error when `abstract` is used outside `frontmatter` (_"Nope nope nope, please put abstract inside the frontmatter environment"_). A warning is possible too; but I suppose an error would be more attention-grabbing for authors to notice the error and the solution. WDYT? Error or Warning?

**Comment by davidlmobley** [comment]
An error sounds great. Thanks!

**Comment by davidlmobley** [comment]
Resolved by #45 , @dwsideriusNIST

**Comment by dwsideriusNIST** [comment]
Thanks, this works for me!
