### ISSUE TITLE
Reference formatting: should pMID's be in the references?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/article_templates#62]
Not sure. Looks inconsistent, maybe overkill, but thoughts?

**Comment by davidlmobley** [comment]
I would say no. Any argument for having them?

**Comment by mrshirts** [comment]
Not really.  One of the articles (Transport) had them.

**Comment by dwsideriusNIST** [comment]
We addressed this awhile ago: https://github.com/livecomsjournal/article_templates/blob/master/bibliography_guidelines.md

- A reference must contain no more than one electronic link. The order of preference for the link is:
  * DOI
  * Publisher URL
  * some other ID
- The vancouver-livecoms.bst style will prefer to include the DOI, and suppress a separate URL, if the DOI is supplied, so that only one electronic link is included in the citation.

It was pretty straightforward to ignore URL if DOI is included, but I'd need help on the RPN needed to ignore pMID.

**Comment by dwsideriusNIST** [comment]
I reviewed this issue and recommend that it be closed. We've already written the BST file to prefer DOI over URL. But to create a ranked list of external identifiers would require that we anticipate every possible variation - it's not feasible. So, my opinion is that the authors have to take responsibility to include only one external ID in their BIB file, following the publication guidelines. Let's add it to the authors' checklist (https://github.com/livecomsjournal/livecomsjournal.github.io/issues/107)

Please close this issue.

**Comment by davidlmobley** [comment]
Thanks!
