### ISSUE TITLE
Posting DOI's properly in articles and on website

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/article_templates#66]
See the following for how we are supposed to include DOI's in article information; this should be reflected in the article templates (potentially in the web site as well).
https://www.crossref.org/display-guidelines/

**Comment by dwsideriusNIST** [comment]
I'll get to work on the templates and latex files. We'll have to ask the papers that are already online to sync-up the CLS and BST files and recompile.

**Comment by mrshirts** [comment]
They know there will be a last pass before moving from ASAP to published issue - if they are willing to do one more intermediate step, then that would be nice.  :)

**Comment by dwsideriusNIST** [comment]
One corollary that I can address before PR #67 is reviewed:

Do we want to include the issue number in the footer? I notice that the citation is being given as:

volume.issue.articleID (e.g., https://doi.org/10.33011/livecoms.1.1.5067)

**Comment by davidlmobley** [comment]
@mrshirts @dmzuckerman what do you think about issue number in the footer? I don't particularly care since the article seems like the primary important thing (in fact I'd argue against it just based on the idea that I think each article should be stand-alone and this is a way to help people think that way) but I don't feel that strongly about it.

**Comment by davidlmobley** [comment]
Once @dwsideriusNIST has this in the templates, ping me and I'll check the website content.

Responses are going to be slow for me for a while; dealing with two grant proposals before Christmas.

**Comment by mrshirts** [comment]
Good question. the final article version will be the one released with the issue, so it wouldn't hurt the workflow at all.  So I don't see any problem with it.  Since it's now clearly in the DOI as well :)

**Comment by davidlmobley** [comment]
@mrshirts I am not quite sure which side of this you come down on then; "I don't see any problem with it" is a little ambiguous since Dan asked about whether we WANTED to include the issue number in the footer and I advocated for NOT including it in the footer; I'm unclear whether "I don't see any problem with it" means "I don't see any problem with including it in the footer" or "I don't see any problem with leaving it out of the footer."

What's your take?

**Comment by mrshirts** [comment]
Sorry, I meant I don't see any problem with having it in the footer.

**Comment by dwsideriusNIST** [comment]
See PR #68 for update to CLS and sample TeX that includes the issue number in the footer.
